name: 'Build & Release'

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Automated Version Bump 🏷
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        with:
          commit-message: '🤖 CI: bumps version to {{version}} [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Output Step 📣
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: master
          folder: docs
          target-folder: docs
          commit-message: '🤖 CI: deploy website to github pages [skip ci]'